# Generated by Django 2.0.3 on 2018-04-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='finie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partie',
            name='player1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Joueur des blancs'),
        ),
        migrations.AddField(
            model_name='partie',
            name='player2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Joueur des noirs'),
        ),
    ]
