# Generated by Django 2.0.3 on 2018-04-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dames', '0002_auto_20180407_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partie',
            name='finie',
        ),
        migrations.AlterField(
            model_name='partie',
            name='data',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Données JSON'),
        ),
    ]
