# Generated by Django 2.0.3 on 2018-04-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dames', '0003_auto_20180407_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='player1_turn',
            field=models.BooleanField(default=False, verbose_name="C'est au tour des blancs"),
        ),
    ]
