# Generated by Django 2.0.3 on 2018-03-20 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023, verbose_name='Nom de la propriété')),
                ('value', models.CharField(blank=True, max_length=4095, verbose_name='Description & valeur')),
            ],
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la machine')),
                ('dns', models.CharField(max_length=255, verbose_name='Nom de domaine')),
                ('ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('description', models.CharField(max_length=2047, verbose_name='Description')),
                ('up', models.BooleanField(default=False, verbose_name='Allumé ?')),
                ('state', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Down'), (2, 'Up'), (3, 'Internet'), (4, 'Working'), (5, 'Up-to-date')], verbose_name='État')),
                ('lastseen', models.DateTimeField(auto_now=True, verbose_name='Dernier accès/update')),
            ],
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='status.HostStatus', verbose_name='Machine'),
        ),
    ]
