# Generated by Django 2.0.3 on 2018-03-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='Adresse IP'),
        ),
    ]
