# Generated by Django 2.0.3 on 2018-03-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023, verbose_name='Nom de la propriété')),
                ('value', models.CharField(blank=True, max_length=4095, verbose_name='Description & valeur')),
            ],
            options={
                'verbose_name': 'Détails machine',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2047, verbose_name='Description')),
                ('dns', models.CharField(max_length=255, verbose_name='Nom de domaine')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la machine')),
                ('chassis', models.IntegerField(choices=[('rack', 'Serveur Rack'), ('tower', 'Format Tour'), ('laptop', 'Ordinateur portable')], verbose_name='Chassis')),
                ('use_case', models.IntegerField(choices=[('personal', 'Personal'), ('family', 'PC familial'), ('server', 'Serveur')], verbose_name="Type d'utilisation")),
                ('power_action', models.CharField(choices=[('none', 'Non disponible'), ('start', 'Démarrer'), ('reboot', 'Redémarrer'), ('poweroff', 'Éteindre et Allumer, redémarrer'), ('suspend', 'Veille et démarrer'), ('rtcwake', 'Arrêt temporaire')], max_length=255, verbose_name="Gestion de l'alimentation")),
            ],
            options={
                'verbose_name': 'Machine',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('up', models.BooleanField(default=False, verbose_name='Allumé ?')),
                ('state', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Down'), (2, 'Up'), (3, 'Internet'), (4, 'Working'), (5, 'Up-to-date')], verbose_name='État')),
                ('lastseen', models.DateTimeField(auto_now=True, verbose_name='Dernier accès/update')),
                ('remote_capable', models.BooleanField(verbose_name='Accès à distance possible')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='status.Host', verbose_name='Machine')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status des machines',
            },
        ),
        migrations.RemoveField(
            model_name='additionalinfo',
            name='host',
        ),
        migrations.DeleteModel(
            name='AdditionalInfo',
        ),
        migrations.DeleteModel(
            name='HostStatus',
        ),
        migrations.AddField(
            model_name='detail',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='status.Host', verbose_name='Machine'),
        ),
    ]
