# Generated by Django 2.0.3 on 2018-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180322_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='chassis',
            field=models.CharField(choices=[('rack', 'Serveur Rack'), ('tower', 'Format Tour'), ('laptop', 'Ordinateur portable')], max_length=255, verbose_name='Chassis'),
        ),
        migrations.AlterField(
            model_name='host',
            name='use_case',
            field=models.CharField(choices=[('personal', 'Personal'), ('family', 'PC familial'), ('server', 'Serveur')], max_length=255, verbose_name="Type d'utilisation"),
        ),
    ]
