# Generated by Django 2.0.3 on 2018-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180322_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='local_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='IP locale'),
        ),
    ]
