# Generated by Django 2.0.3 on 2018-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_status_local_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='remote_capable',
        ),
        migrations.AddField(
            model_name='host',
            name='remote_capable',
            field=models.BooleanField(default=False, verbose_name='Accès à distance possible'),
        ),
    ]
